### ISSUE TITLE
videosdk-ui-toolkit.js:3 ERROR TypeError: Cannot use 'in' operator to search for 'getDisplayMedia' in undefined

### ISSUE THREAD

**Issue by D0nVitalio** [zoom/videosdk-ui-toolkit-javascript-sample#1]
Hi!
Have latest Chrome, Win10, Xampp, cloned this repo, then edited index.js as written in Setup, checked that `http://localhost:4000` returned `{"signature": "eyJh...`  and opened local address. No 400 errors.
Got this:
![image](https://github.com/user-attachments/assets/a67d7d83-d185-45f1-9b27-1d1a360fee70)
Pressed Join
and got white button in center,
![image](https://github.com/user-attachments/assets/a0db5da1-b4a2-4c5a-b5da-b7ae30b64663)
and errors in console
![image](https://github.com/user-attachments/assets/432d19f6-d310-4a11-bd80-bb87f9b099cc)

Could you please help me solve that problem?

![image](https://github.com/user-attachments/assets/0c3048e0-2506-4e61-ba6d-368c3f1b9a6a)

**Comment by tommygaessler** [comment]
Hey @D0nVitalio , can you send me your config object please?

**Comment by D0nVitalio** [comment]
> Hey @D0nVitalio , can you send me your config object please?

Config object was on last image in my first message, here is text version that I put in `index.js`

```
var authEndpoint = 'http://localhost:4000'
var config = {
    videoSDKJWT: '',
    sessionName: 'test',
    userName: 'ZoomDev',
    sessionPasscode: '123',
    features: ['preview', 'video', 'audio', 'settings', 'users', 'chat', 'share'],
    options: { init: {}, audio: {}, video: {}, share: {}},
    virtualBackground: {
        allowVirtualBackground: true,
        allowVirtualBackgroundUpload: true,
        virtualBackgrounds: ['https://images.unsplash.com/photo-1715490187538-30a365fa05bd?q=80&w=1945&auto=format&fit=crop']
    }
};
var role = 1
export default {...
```

**Comment by D0nVitalio** [comment]
Good news!
I have installed ssl certificate in Xampp and all is working, except little bug(?)
When I enable camera  befor enter session, I don't see my little preview on top
![image](https://github.com/user-attachments/assets/6d08f2a2-da14-4a13-8d6a-9ebf15063593)

but if I switch off and then on camera
![image](https://github.com/user-attachments/assets/e810d5c5-e439-4210-9e46-aeba6bf0cae1)

then preview is working
![image](https://github.com/user-attachments/assets/e4a41350-cf9f-493d-b9be-3414aa5e3b7a)

I guess you can close that ticket.

Also I would appreciate if you can help me remove that↑ little bug)

Thanks for the fast answer!

**Comment by D0nVitalio** [comment]
On https prod set headers as in [](https://developers.zoom.us/docs/meeting-sdk/web/sharedarraybuffer/) , added `coi-serviceworker.js` and all works.

**Comment by tommygaessler** [comment]
Hey @D0nVitalio , happy to hear you got it working! 

For the start video button I am not able to reproduce the issue. Were there any errors in the browser console and which browser are you using?
