### ISSUE TITLE
Correct JWT not accepted

### ISSUE THREAD

**Issue by D0nVitalio** [zoom/videosdk-ui-toolkit-javascript-sample#2]
Hi,
there is one more strange thing.
I have been creating JWT with https://github.com/zoom/videosdk-auth-endpoint-sample and these JWT are working ok.
On my backend I want to use PHP
`\Firebase\JWT\JWT::encode($payload, $data['sdkSecret'], 'HS256',null,['alg'=>'HS256', 'typ'=>'JWT']);`
That PHP JWT is creating correct JWT's for Meeting SDK, so asume I can create correct JWTs with PHP.

Problem is that PHP JWTs not working.
I have checked them this way:
```
dump('SDK-auth-endpoint', \Firebase\JWT\JWT::decode('eyJ...zuE', new \Firebase\JWT\Key($data['sdkSecret'],'HS256') ));
dump('PHP', \Firebase\JWT\JWT::decode('eyJ...rTU', new \Firebase\JWT\Key($data['sdkSecret'],'HS256') ));
```
and by inserting them with SDK_SECRET to https://jwt.io 
- both checks shows, that that PHP JWTs and JS JWTs are correct and differs only in iat and exp and both of these parameters are correct.

My payload dump:
```
+"app_key": "ab..cd"
  +"role_type": 0
  +"tpc": "php"
  +"version": 1
  +"iat": 1726834413
  +"exp": 1726838013

```
JS payload dump:
```
+"app_key": "ab..cd"
  +"role_type": 0
  +"tpc": "test-oks"
  +"version": 1
  +"iat": 1726833523
  +"exp": 1726840723
```
Dump of auth endpoint:
```
JSON.stringify(oPayload) {"app_key":"ab..cd","role_type":0,"tpc":"test-oks","version":1,"iat":1726833523,"exp":1726840723} 
JSON.stringify(oHeader)  {"alg":"HS256","typ":"JWT"}
```

Also when use PHP JWT, see this for 5 sec:
![image](https://github.com/user-attachments/assets/7fa94ff0-77d2-4440-9968-f95a025a1622)

Do you have an idea why correct PHP JWT is not accepted?

**Comment by D0nVitalio** [comment]
Forgot about adding payload with parameters from script.js

**Comment by tommygaessler** [comment]
Hey @D0nVitalio , happy to hear you got it working! :)
