### ISSUE TITLE
Errors on joinSession() are not correctly logged

### ISSUE THREAD

**Issue by bojcicm** [zoom/videosdk-ui-toolkit-javascript-sample#3]
If error occurs after line 
```js
yield e.joinSession()
```
In catch block it doesnt handle error correctly.
On UI it will display message `UIKit: [Object object]` 
No logs in console, couldn't figure out what was wrong.

In minified file I had to update catch logic after `joinSession()`
Instead of
```js
catch(i) {
  e.error.throw("UIKit", i);
  e.isLoading = false;
}
```
I have changed it to
```js
catch(i) {
  e.error.throw("UIKit", i.reason);
  console.error(i);
  e.isLoading = false;
}
```

**Comment by bojcicm** [comment]
https://github.com/zoom/videosdk-ui-toolkit-web/issues/35

**Comment by tommygaessler** [comment]
Thank you for the feedback @bojcicm , we will work on this and update you in the main repo as you linked to.
